name: Scheduled Proxy

on:
  schedule:
    - cron: '0 14 * * 0-6' 

jobs:
  trigger-target:
    runs-on: ubuntu-latest
    steps:
      - name: Call workflow_dispatch in another branch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TOKEN_DISPATCH }}
          repository: ${{ github.repository }}
          event-type: scheduled-workflow
          client-payload: '{"ref": "dev"}'
