name: Test Workflow

on:
  repository_dispatch:
    types: [scheduled-workflow]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow déclenché automatiquement !"


schedule: 
    # Runs "At 01:00 on every day-of-week from Monday through Sunday."
    - cron: '0 1 * * 0-6'